name: Check For New Translations
run-name: ${{ github.actor }} is checking for new translations! 🚀
on: pull_request
permissions:
  contents: read # this is necessary for the Action to be able to read the contents of the repo
  pull-requests: write
jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Check Changed Files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: GrantBirki/git-diff-action@v2.8.1
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"
      - name: Fetch Current Localized Text
        id: fetch-translations
        shell: bash
        run: |
           curl -X POST -H "Content-Type: application/json" -d '{"locale": "fr"}' --cookie-jar ./cookies https://sm.dozuki.com/api/2.0/translations/settings
           currentTranslations=$(curl -b ./cookies https://sm.dozuki.com/api/2.0/translations)
           echo "$currentTranslations" >> ./.github/scripts/current_translations.json
      - name: Parse Changes Via Script
        id: parse-changes
        run: |
          newStrings=$(node ExtractTranslations.ts)
          # echo $newStrings
          echo "NEW_STRINGS=$newStrings" >> $GITHUB_OUTPUT
        working-directory: ./.github/scripts
      - name: Send localized string change notification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -d "{\"body\":\"${{ steps.parse-changes.outputs.NEW_STRINGS }}\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
        
