name: Check For New Translations
run-name: ${{ github.actor }} is checking for new translations! 🚀
on: pull_request
permissions:
  contents: read # this is necessary for the Action to be able to read the contents of the repo
  pull-requests: write
jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Checking Changed Files...
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: GrantBirki/git-diff-action@v2.8.1
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"
      - name: Parse Changes
        id: parse-changes
        working-directory: ./dev
        run: |
          diffResult=$(node diffContainsTranslations.js)
          echo "HAS_CHANGES=$diffResult" >> $GITHUB_OUTPUT

          
